import React from 'react';
import { GetStaticProps } from 'next';
import Head from 'next/head'
import Image from 'next/image'
import { GraphQLClient, gql } from 'graphql-request';
import { documentToReactComponents } from '@contentful/rich-text-react-renderer';
import type { Document } from '@contentful/rich-text-types';

import styles from '../styles/Home.module.css'

interface Props {
  posts: {
    blogPostCollection: {
      items: {
        title: string;
        publishedAt: Date;
        content: { json: Document }
      }[];
    }
  }
}

export const getStaticProps: GetStaticProps<Props> = async () => {
  const gqlClient = new GraphQLClient(`https://graphql.contentful.com/content/v1/spaces/${
    process.env.SPACE_ID
  }`, {
    headers: {
      Authorization: `Bearer ${process.env.CDA_TOKEN}`,
    }
  });

  const postsQuery = gql`
    {
      blogPostCollection {
        items {
          title
          content {
            json
          }
          publishedAt
        }
      }
    }
  `;

  const posts = await gqlClient.request(postsQuery);

  return {
    props: {
      posts,
    }
  }
};

export default function Home(props: Props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {props.posts.blogPostCollection.items.map(({ title, publishedAt, content }) => (
          <div key={title}>
            <h2>{title}</h2>
            <p>{publishedAt.toLocaleString()}</p>
            {documentToReactComponents(content.json)}
          </div>
        ))}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
